- name: Fetch git information
  import_tasks: tasks/git-info.yml

- name: Remove existing production bundle
  file:
    path: ../build
    state: absent

- name: Build production bundle
  shell: |
    cd ../ && \
      yarn install && \
      yarn build

- name: Build Docker image
  shell: |
    docker build \
      -f docker/Dockerfile \
      -t video-downloader-front-end:latest \
      -t video-downloader-front-end:{{ git_commit }} \
      -t video-downloader-front-end:{{ git_branch }}-{{ ansible_date_time.iso8601_basic_short }} \
      ../
