---
- hosts: localhost
  connection: local

  tasks:
    - name: Fetch git information
      import_tasks: tasks/git-info.yml

    - set_fact:
        namespace: "{{ 'video-downloader-front-end' if  git_branch == 'master' else 'video-downloader-front-end-' + git_branch }}"

    - name: Create K8s resource files
      import_tasks: tasks/k8s-resource-files.yml
      vars:
        hostname: "{{ 'video.home.ruchij.com' if  git_branch == 'master' else git_branch + '.video.home.ruchij.com' }}"

    - name: Create kubeconfig
      import_tasks: tasks/k8s-config.yml

    - name: Deploy to K8s
      block:
        - name: Create Namespace
          command: kubectl apply -f k8s-output/Namespace.yaml --kubeconfig k8s-output/kubeconfig

        - name: Deploy application
          command: kubectl apply -f k8s-output --kubeconfig k8s-output/kubeconfig

        - name: Wait for successful deployment
          command: kubectl rollout status deployment front-end-deployment --kubeconfig k8s-output/kubeconfig -n {{ namespace }}

    - name: Delete output directory
      file:
        path: k8s-output
        state: absent
