---
- hosts: localhost
  connection: local

  tasks:
    - name: Fetch git information
      import_tasks: tasks/git-info.yml

    - name: Create K8s resource files
      import_tasks: tasks/k8s-resource-files.yml
      vars:
        docker_registry: localhost:32000
        hostname: "{{ git_branch }}.video.local.ruchij.com"

    - name: Create kubeconfig
      import_tasks: tasks/k8s-config.yml
      vars:
        aws_ssm_k8s_config_path: /k8s/config/ubuntu-vm

    - name: Deploy to K8s
      block:
        - name: Create Namespace
          command: kubectl apply -f k8s-output/Namespace.yaml --kubeconfig k8s-output/kubeconfig

        - name: Deploy application
          command: kubectl apply -f k8s-output --kubeconfig k8s-output/kubeconfig

        - name: Wait for successful deployment
          command: kubectl rollout status deployment front-end-deployment --kubeconfig k8s-output/kubeconfig -n video-downloader-front-end-{{ git_branch }}

    - name: Delete output directory
      file:
        path: k8s-output
        state: absent
